name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build Linux amd64 Binary
      run: env GOOS=linux GOARCH=amd64 go build -v -o build/sqlitetool_linux_amd64 ./cmd/sqlitetool

    - name: Build Linux arm64 Binary
      run: env GOOS=linux GOARCH=arm64 go build -v -o build/sqlitetool_linux_arm64 ./cmd/sqlitetool
  
    - name: Build Darwin amd64 Binary
      run: env GOOS=darwin GOARCH=amd64 go build -v -o build/sqlitetool_darwin_amd64 ./cmd/sqlitetool
      
    - name: Build Darwin arm64 Binary
      run: env GOOS=darwin GOARCH=arm64 go build -v -o build/sqlitetool_darwin_arm64 ./cmd/sqlitetool
      
    - name: Build Windows amd64 Binary
      run: env GOOS=windows GOARCH=amd64 go build -v -o build/sqlitetool_windows_amd64.exe ./cmd/sqlitetool

    - uses: actions/upload-artifact@v3
      with:
        name: sqlitetool
        path: build/
